  name = "cadmospayrecovery"
  main = "worker.js"
  compatibility_date = "2026-02-06"

  [build]
  command = "npm run build:frontend"
  watch_dir = ["frontend", "shared", "scripts"]

  [assets]
  directory = "./dist"
  binding = "ASSETS"
